# Base URL of the site, the only required config argument
base_url = "https://harshil-jani.netlify.app/"

title = "Harshil Jani"
description = "My blog"
default_language = "en"

# Theme name to use
# theme = ""

# Highlight all code blocks found
# Or enable the highlight.js in the 'extra' config section
highlight_code = false

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "agola-dark"


# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
           {name = "tags", rss = true}
]

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true

# Whether to build a search index out of the pages and section
# content for the `default_language`
build_search_index = false

# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

# Optional translation object. The key if present should be a language code
[translations]

# You can put any kind of data in there and it
# will be accessible in all templates
[extra]

home_subtitle = "Engineering Student, Linux Learner, Working to transform governance, Environment emphasizer, Google Summer of Code Student 2022 @ CERN-HSF"

harshil_menu = [
    { link = "/blogs", name = "Blogs" },
    { link = "/about", name = "About" },
    { link = "/resume", name = "Resume" },
    { link = "/gsoc", name="Google Summer Of Code'22"}
]

harshil_social = [
    { name = "twitter", link = "https://twitter.com/harshil_jani28" },
    { name = "github", link = "https://github.com/Harshil-Jani" },
    { name = "email", link = "mailto:harshiljani2002@gmail.com" },
    { name = "gitlab", link = "https://gitlab.com/Harshil-Jani" },
    { name = "linkedin", link = "https://linkedin.com/harshil1" },
    { name = "slack", link = "https://app.slack.com/client/T5CSCA08L/C01HXSME998/rimeto_profile/U034K2X4TQF" }   
]


# You can use highlight.js for code highlighting if you dont like the 
# default one
[extra.highlightjs]
enable = true
clipboard = true
theme = "railscasts"

# [extra.disqus]
# enable = false
# # Take this from your Disqus account
# shortname = "my-supa-dupa-blog"
# # Cpmments can be disabled per page by setting:
# # [extra]
# # disable_comments = true
# #
# # in the posts front-matter


[extra.author]
name = "Harshil Jani"
email = "harshiljani2002@gmail.com"
